# Generated by Django 5.1.4 on 2025-05-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0003_flightstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightstatus',
            name='status',
            field=models.CharField(choices=[('Scheduled ', 'Scheduled '), ('Delayed ', 'Delayed '), ('Departed', 'Departed'), ('In Air', 'In Air'), ('Landed', 'Landed'), ('Arrived', 'Arrived'), ('Cancelled', 'Cancelled '), ('Expected', 'Expected'), ('Past Flight', 'Past Flight'), ('Diverted', 'Diverted')], default='Scheduled', max_length=15),
        ),
    ]
